### ISSUE TITLE
Build 626 dropped translations support

### ISSUE THREAD

**Issue by KorneySan** [JOSM/pt_assistant#56]
After updating to the build 626 I found that ALL plugin texts become untranslated.

I'm a translator on Transifex and some time ago completed translation to my language. Was awaiting for update to see all missing strings and suddenly didn't found any translation at all!

**Comment by tsmock** [comment]
I'll check and see what happened. But can you tell me what specific language is the problem?

Best guess, based off of past experiences, is that there is a mismatch between the text to translate since the last transifex update (see https://gitlab.com/JOSM/plugin/pt_assistant/-/pipelines -- it doesn't look like the repo is running _any_ pipelines, so I'll see how easy that is to fix).

**Comment by tsmock** [comment]
Let me know if v627 fixes the problem.

**Comment by KorneySan** [comment]
I'm sorry, but it didn't.
Nothing changed.
![Image 411 1](https://user-images.githubusercontent.com/20338527/225836132-84fc257d-b19a-44dc-8f4d-a20d06486841.png)

**Comment by tsmock** [comment]
It looks like the `ant` build script doesn't deal with the po files from transifex. I'll have to look into how to fix that. In the meantime, I've uploaded a new jar to v627.

**Comment by KorneySan** [comment]
Thanks, now it is much better, at least with Russian language (code `ru`). See screenshots.
![Image 3033](https://user-images.githubusercontent.com/20338527/226092124-36ddf9c8-7ed5-4ceb-bc45-ea8d9691a11e.png)
Settings menu item and description are translated.

![Image 3034](https://user-images.githubusercontent.com/20338527/226092360-2c3815c3-9f7f-41f5-b19d-99aa48d2000b.png)
Plugin settings are translated (headers was never been translated).

![Image 3035 1](https://user-images.githubusercontent.com/20338527/226092178-115a4b60-884a-4ed8-a064-116aae70ad95.png)
Program menu items are translated completely (were translated partially before).

![Image 3036 1](https://user-images.githubusercontent.com/20338527/226092236-55a5161d-dcb7-46d6-959f-9400fc5f5402.png)
"Customize stop" dialog is translated completely (was before except some strings).

Belarusian language (code `be`) is worse.
![Image 3029](https://user-images.githubusercontent.com/20338527/226092427-2166fe68-b2be-4972-83f5-2b50278d68cf.png)
Settings menu item is not translated (but description is!)

![Image 3030](https://user-images.githubusercontent.com/20338527/226092468-30c3d33e-f72f-499e-88b9-d8255d6eebd3.png)
Plugin settings are NOT translated at all.

![Image 3031 1](https://user-images.githubusercontent.com/20338527/226092552-932892fc-b163-45af-ae32-58382cdaba74.png)
Program menu items are translated partially, like in Russian before you started.

![Image 3032 1](https://user-images.githubusercontent.com/20338527/226092628-48c39473-1335-4156-a8ac-e5612ea34f9a.png)
"Customize stop" dialog is translated partially.

I hope these pictures will help you to deal with it.
