### ISSUE TITLE
Unable to use plugin with JOSM Stable release

### ISSUE THREAD

**Issue by Mhowser** [JOSM/pt_assistant#63]
JOSM version: 18822

Is this intentional? do we need to use the Development version from now on?

**Comment by tsmock** [comment]
No; it looks like the old version links aren't being added via `build.xml`. It _should_ be an easy fix.

```
pt_assistant.jar;https://github.com/JOSM/pt_assistant/releases/latest/download/pt_assistant.jar
	Manifest-Version: 1.0
	Ant-Version: Apache Ant 1.10.14
	Created-By: 11.0.21+9 (Eclipse Adoptium)
	Plugin-Mainversion: 18877
	Plugin-Version: 631
	Plugin-Class: org.openstreetmap.josm.plugins.pt_assistant.PTAssistantPlugin
	Plugin-Description: Provides validation and fixing for public transport route according to version 2 of the public transport schema
	Plugin-Date: 2018-09-29 20:09:26 +0000
	Author: Biswesh Mohapatra <biswesh123@gmail.com>, simon04, Rodion Scherbakov
	Plugin-Link: https://wiki.openstreetmap.org/wiki/JOSM/Plugins/PT_Assistant
	Plugin-Icon: data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjMyIiB2aWV3Qm94PSIwIDAgMzIgMzIiIHdpZHRoPSIzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+PHVzZSBzdHJva2U9IiNmZmYiIHN0cm9rZS13aWR0aD0iMy42IiB4bGluazpocmVmPSIjYSIvPjxwYXRoIGlkPSJhIiBkPSJtOS42IDI2LjZ2MmExLjYgMS42IDAgMCAxIC0zLjIgMHYtMmgtMnYtMTJsMS4yLTguNnEuNS0yIDIuOS0yLjggNC45LTEuMyA3LjUtMS4zIDIuNiAwIDcuNSAxLjMgMi44LjcgMi45IDIuOGwxLjIgOC42djEyaC0ydjJhMS42IDEuNiAwIDAgMSAtMy4yIDB2LTJ6bTEuNy0yMi42YS43LjcgMCAwIDAgMCAxLjRoOS40YS43LjcgMCAwIDAgMC0xLjR6bS0yLjcgMi44Yy0uMiAwLTEuMSAwLTEuMyAxLjNsLS44IDYuNXEtLjEgMSAuOSAxaDE3LjJzMSAwIDEtMWwtLjktNi41cS0uMi0xLjMtMS4zLTEuM3ptLS42IDEyLjlhMS42IDEuNiAwIDAgMCAwIDMuMiAxLjYgMS42IDAgMCAwIDAtMy4yem0xNiAwYTEuNiAxLjYgMCAwIDAgMCAzLjIgMS42IDEuNiAwIDAgMCAwLTMuMnoiLz48L3N2Zz4=
	Plugin-Canloadatruntime: true
```

**Comment by stoecker** [comment]
Automatically that only works for SVN plugins ;-)

**Comment by tsmock** [comment]
This is just fallout from (slowly) moving lightly maintained GitHub plugins over to an automatic release cycle. Just so that when we push i18n updates, there is a release for those i18n updates.

I just need to remember to _copy_ the gradle `oldVersionDownloadLink` information into the `build.xml` files. Which isn't ideal, but is currently necessary.

**Comment by stoecker** [comment]
Well, easy. Move the plugin back to SVN ;-)

**Comment by tsmock** [comment]
Technically possible, but I really don't like `svn`. IMO, the only real advantage `svn` has over `git` is better support for large binary blobs. Most everything else that I've seen as advantages for `svn` can also be done with `git`.

Anyway, this repository _currently_ uses Transifex for i18n, and _GitLab_ CI pushes the i18n changes to Transifex. I think I'll start moving it back to be on the same i18n system as JOSM and a good chunk of the plugins.

**Comment by tsmock** [comment]
FML. I just found out that GitHub is going to be removing SVN support on 2024-01-08. So we are going to have to either move to `git` or move everything to `svn`. We won't be able to mix and match.

https://github.blog/2023-01-20-sunsetting-subversion-support/

I haven't read through the blog post yet.
